// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroListOfLists.Records
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ListOfNillablesRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ListOfNillablesRecord\",\"namespace\":\"AvroListOfLists.Reco" +
				"rds\",\"fields\":[{\"name\":\"MyListOfNullables\",\"type\":{\"type\":\"array\",\"items\":[\"null" +
				"\",\"int\"]}}]}");
		private IList<System.Nullable<int>> _MyListOfNullables;
		public virtual Schema Schema
		{
			get
			{
				return ListOfNillablesRecord._SCHEMA;
			}
		}
		public IList<System.Nullable<int>> MyListOfNullables
		{
			get
			{
				return this._MyListOfNullables;
			}
			set
			{
				this._MyListOfNullables = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.MyListOfNullables;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.MyListOfNullables = (IList<System.Nullable<int>>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
