// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroListOfLists.Records
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class MatrixRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"MatrixRecord\",\"namespace\":\"AvroListOfLists.Records\",\"fie" +
				"lds\":[{\"name\":\"MyMatrix\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":" +
				"{\"type\":\"array\",\"items\":\"int\"}}}}]}");
		private IList<IList<IList<System.Int32>>> _MyMatrix;
		public virtual Schema Schema
		{
			get
			{
				return MatrixRecord._SCHEMA;
			}
		}
		public IList<IList<IList<System.Int32>>> MyMatrix
		{
			get
			{
				return this._MyMatrix;
			}
			set
			{
				this._MyMatrix = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.MyMatrix;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.MyMatrix = (IList<IList<IList<System.Int32>>>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
