// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroListOfLists.Records
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class MyIListRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"MyIListRecord\",\"namespace\":\"AvroListOfLists.Records\",\"fi" +
				"elds\":[{\"name\":\"MyIList\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}]}");
		private IList<System.Int32> _MyIList;
		public virtual Schema Schema
		{
			get
			{
				return MyIListRecord._SCHEMA;
			}
		}
		public IList<System.Int32> MyIList
		{
			get
			{
				return this._MyIList;
			}
			set
			{
				this._MyIList = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.MyIList;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.MyIList = (IList<System.Int32>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
